workflows:
  ios-build:
    name: iOS Test Build (Capacitor)
    max_build_duration: 60
    environment:
     
      xcode: latest
      # កំណត់ Node version ព្រោះ Vue.js/Capacitor ប្រើ Node
      node: latest
    
    # ជ្រើសរើស Mac server សម្រាប់ build iOS
    instance_type: mac_mini_m1
    
    scripts:
      - name: Install dependencies (Node Modules)
        # ដំណើរការ npm install ក្នុង folder របស់អ្នក
        script: |
          npm install

      - name: Build Web Code (Vue.js)
        # ដំណើរការ build command របស់ Vue
        script: |
          npm run build

      - name: Sync Web to iOS Native Project
        # ផ្ទេរ code web ចូលទៅក្នុង folder ios
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        # ដំឡើង dependencies របស់ iOS
        script: |
          cd ios
          pod install

      - name: Build Xcode Project (Test Build Only)
        # Command build Xcode
        script: |
          xcode-project build \
            --project "ios/App/App.xcodeproj" \
            --scheme "App" \
            --configuration "Release" \
            # កំណត់ឲ្យ Build ត្រឹមតែ architecture របស់ simulator/device
            --only-archs "arm64 x86_64"

    # ផ្នែកនេះនឹងបរាជ័យព្រោះអ្នកមិនទាន់មាន Apple Developer Account
    # បើចង់ Build ឲ្យចេញ File .ipa ត្រូវបង់លុយ $99/ឆ្នាំ
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
